spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://47.113.103.216:3306/jerry?serverTimezone=UTC&useUnicode=ture&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 47.113.103.216
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: -1
        max-idle: 8
        min-idle: 0
    lettuce:
      shutdown-timeout: 300
#mybatis#
mybatis:
  type-aliases-package: com.sx.daoyun.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

